require('core.plugin_config.lualine')
require('core.plugin_config.comment')
require('core.plugin_config.indent_blankline')
require('core.plugin_config.gitsigns')
require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.nvimtree')
